"""adiciona novas colunas em agendamentos

Revision ID: 90523184e07c
Revises: ec18d06480a8
Create Date: 2025-11-06 12:09:29.096185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90523184e07c'
down_revision: Union[str, Sequence[str], None] = 'ec18d06480a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('n8n_chat_histories')
    op.add_column('agendamentos', sa.Column('lembrete1dia', sa.Boolean(), nullable=True))
    op.add_column('agendamentos', sa.Column('lembrete2horas', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agendamentos', 'lembrete2horas')
    op.drop_column('agendamentos', 'lembrete1dia')
    op.create_table('n8n_chat_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('n8n_chat_histories_pkey'))
    )
    # ### end Alembic commands ###
